# Generated by Django 4.2.7 on 2026-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
